Repository wp-media/imagify-plugin, pull requests merged in 2020-05, with the labels that each got.

#494 Fixes #491: Auto-optimization on image upload doesn't optimize thumbnails
  inc/classes/class-imagify-auto-optimization.php
  inc/deprecated/classes/class-imagify-auto-optimization-deprecated.php
Labels: Severity: major, Type: bug, needs: qa

#497 Fixes #493: compatibility with plugin "Enable Media Replace" broken with WP 5.3
  inc/3rd-party/enable-media-replace/classes/Main.php
  inc/3rd-party/enable-media-replace/enable-media-replace.php
  inc/classes/class-imagify-auto-optimization.php
  inc/deprecated/classes/class-imagify-auto-optimization-deprecated.php
  inc/deprecated/classes/class-imagify-enable-media-replace-deprecated.php
Labels: 3rd Party Compatibility, Type: bug, needs: qa

#500 v1.9.10
  imagify.php
  inc/3rd-party/enable-media-replace/classes/Main.php
  inc/3rd-party/enable-media-replace/enable-media-replace.php
  inc/classes/class-imagify-auto-optimization.php
  inc/deprecated/classes/class-imagify-auto-optimization-deprecated.php
  inc/deprecated/classes/class-imagify-enable-media-replace-deprecated.php
  readme.txt
Labels: Type: bug
