Repository wp-media/imagify-plugin, pull requests merged in 2021-07, with the labels that each got.

#579 Fix #511 - Remove old coupon code and related text
  views/notice-wp-rocket.php
Labels: bugfix

#583 Closes #561 Centralize App URL definition
  assets/js/pricing-modal.js
  assets/js/pricing-modal.min.js
  imagify.php
  inc/classes/class-imagify.php
  inc/functions/common.php
  inc/functions/i18n.php
Labels: type: enhancement

#590 Fix #537 Stop replacing images already nested inside picture tags
  classes/Webp/Picture/Display.php
Labels: module: convert webp, type: bug

#578 Fix #564 - Improve filter for Imagify Notices
  inc/classes/class-imagify-notices.php
Labels: 3rd party compatibility, priority: medium, type: enhancement

#587 Fixes #495 Webp compatibility with WooCommerce variable product images
  inc/3rd-party/3rd-party.php
  inc/3rd-party/WooCommerce/class-woocommerce.php
Labels: 3rd party compatibility, module: convert webp, severity: major, type: bug

#598 Fix #573 - PHP Notice when user has no image count
  inc/classes/class-imagify-cron-rating.php
Labels: needs: qa, type: bug

#601 Fix #565 - Array Flip fails on non-string item
  inc/classes/class-imagify-admin-ajax-post.php
Labels: type: bug

#600 Update composer, CI and tests for PHP8 support
  .github/workflows/test_php8.yml
  .github/workflows/test_plugin_legacy.yml
  Tests/Integration/inc/classes/ImagifyUser/getError.php
  Tests/Integration/inc/classes/ImagifyUser/getPercentConsumedQuota.php
  Tests/Integration/inc/classes/ImagifyUser/isOverQuota.php
  Tests/TestCaseTrait.php
  composer.json
Labels: devops, type: enhancement

#599 Update requirements and version for 1.10
  imagify.php
  inc/classes/class-imagify-plugin.php
  inc/classes/class-imagify-user.php
  inc/functions/compat.php
  phpcs.xml
  readme.txt
Labels: type: enhancement

#582 Fixes #567 Prevent fatal error related to get_current_screen()
  inc/3rd-party/yoast-seo.php
Labels: 3rd party compatibility, severity: critical, type: bug

#593 fix pricing table and coupon input
  assets/css/admin-bar.min.css
  assets/css/admin.css
  assets/css/admin.min.css
  assets/css/bulk.min.css
  assets/css/files-list.min.css
  assets/css/notices.min.css
  assets/css/options.min.css
  assets/css/pricing-modal.min.css
  assets/css/sweetalert-custom.min.css
  assets/css/sweetalert2.min.css
  assets/css/twentytwenty.min.css
  assets/js/admin-bar.min.js
  assets/js/admin.min.js
  assets/js/beat.min.js
  assets/js/bulk.min.js
  assets/js/files-list.min.js
  assets/js/jquery.event.move.min.js
  assets/js/jquery.twentytwenty.min.js
  assets/js/library.min.js
  assets/js/media-modal.min.js
  assets/js/notices.min.js
  assets/js/options.min.js
  assets/js/pricing-modal.js
  assets/js/pricing-modal.min.js
  inc/functions/i18n.php
Labels: UI, severity: minor, type: bug
