Repository wp-media/imagify-plugin, pull requests merged in 2021-04, with the labels that each got.

#554 Fix: WP 5.7 Cover Blocks not displaying correctly with webp/picture tags enabled
  classes/Webp/Picture/Display.php
Labels: Type: enhancement, community

#555 Use new promotion api data to specify applied plans in banner
  assets/js/pricing-modal.js
  assets/js/pricing-modal.min.js
  views/part-discount-banner.php
Labels: Type: enhancement, needs: qa

#560 Fixes #519 Use correct URLs for images in readme
  README.md
Labels: Severity: trivial, Type: bug
