Repository wp-media/imagify-plugin, pull requests merged in 2022-12, with the labels that each got.

#682 Guard against php8.0 ArgumentCountError
  inc/classes/class-imagify-custom-folders.php
Labels: type: bug

#700 Closes #611 Add webp to the mime types optimized by imagify
  inc/functions/attachments.php
Labels: type: enhancement

#701 Closes #662 Remove plan type display on settings & bulk optimization pages
  views/page-bulk.php
  views/part-settings-account.php
Labels: type: enhancement, UI

#702 Closes #69 Only display plan selection block if on free plan
  views/part-settings-account.php
Labels: type: enhancement

#703 Closes #637 Update message displayed when an unknown error occurred
  inc/functions/api.php
Labels: type: enhancement
