Repository wp-media/imagify-plugin, pull requests merged in 2022-05, with the labels that each got.

#621 [i18n] Fix typos on translatable strings
  assets/js/pricing-modal.js
  inc/functions/i18n.php
  views/modal-payment.php
Labels: type: bug, i18n

#666 Prevent PHP warning when displaying pricing modal with packs removed from API
  inc/classes/class-imagify-admin-ajax-post.php
  inc/classes/class-imagify.php
  inc/functions/api.php
Labels: type: bug

#653 Add filter tag 'imagify_process_webp_content'
  classes/Webp/Picture/Display.php
Labels: type: enhancement, type: new feature

#669 Closes #667 Update plugin author to WP Rocket
  imagify.php
  phpcs.xml
Labels: type: enhancement

#665 Fixes #612 Add missing url parameter to the filter
  inc/classes/class-imagify.php
Labels: type: bug, 3rd party compatibility
