Repository wp-media/imagify-plugin, pull requests merged in 2024-10, with the labels that each got.

#900 Closes #2883: Imagify Plugin - Replace the documentation link with the upgrade one for Free users
  Tests/Fixtures/classes/Admin/AdminSubscriber/pluginActionLinks.php
  Tests/Unit/classes/Admin/AdminSubscriber/pluginActionLinks.php
  Tests/Unit/inc/classes/ImagifyUser/getError.php
  Tests/Unit/inc/classes/ImagifyUser/getPercentConsumedQuota.php
  Tests/Unit/inc/classes/ImagifyUser/isOverQuota.php
  Tests/Unit/phpunit.xml.dist
  assets/css/admin-bar.css
  assets/css/admin-bar.min.css
  classes/Admin/AdminSubscriber.php
  classes/Admin/ServiceProvider.php
  classes/User/User.php
  config/providers.php
  inc/classes/class-imagify-views.php
Labels: type: enhancement, UI

#901 Closes #898 Update close icon on upsell banners and admin bar
  assets/css/admin-bar.css
  assets/css/admin-bar.min.css
  assets/css/admin.css
  assets/css/admin.min.css
  assets/css/bulk.css
  assets/css/bulk.min.css
  assets/css/notices.css
  assets/css/notices.min.css
  views/admin/admin-bar-status.php
  views/part-upsell.php
Labels: type: enhancement

#899 Closes #2884 Upgrade plan link in admin bar
  assets/css/admin-bar.css
  assets/css/admin-bar.min.css
  assets/js/pricing-modal.js
  assets/js/pricing-modal.min.js
  classes/Admin/AdminBar.php
  classes/Admin/ServiceProvider.php
  classes/Plugin.php
  config/providers.php
  inc/classes/class-imagify-assets.php
  inc/classes/class-imagify-views.php
  inc/common/admin-bar.php
  views/admin/admin-bar-status.php
  views/page-bulk.php
  views/page-settings.php
  views/part-upsell.php
Labels: type: enhancement

#907 Cache user API call for 5 minutes
  Tests/Unit/inc/classes/ImagifyUser/getError.php
  Tests/Unit/inc/classes/ImagifyUser/getPercentConsumedQuota.php
  Tests/Unit/inc/classes/ImagifyUser/isOverQuota.php
  Tests/bootstrap-functions.php
  classes/User/User.php
Labels: type: bug
