Repository wp-media/imagify-plugin, pull requests merged in 2024-02, with the labels that each got.

#800 Fixes #791 Update texts related to WebP and Next-Gen
  inc/classes/class-imagify-files-list-table.php
  inc/functions/admin-ui.php
  views/button/delete-webp.php
  views/button/generate-webp.php
  views/part-settings-webp.php
Labels: type: bug, AVIF

#805 Fixes #789 Fix error displayed when using generate missing next-gen versions button
  assets/js/options.js
  inc/functions/api.php
  inc/functions/attachments.php
Labels: type: bug, AVIF

#809 Fixes #788 Generate next-gen formats on image upload
  classes/Optimization/Process/AbstractProcess.php
  classes/Optimization/Process/Noop.php
  classes/Optimization/Process/ProcessInterface.php
Labels: type: bug, AVIF

#811 Closes #796: Auto AVIF Convertion on settings save
  classes/Optimization/File.php
  classes/Optimization/Process/AbstractProcess.php
  inc/classes/class-imagify-admin-ajax-post.php
  inc/common/attachments.php
Labels: AVIF

#823 Closes #822: The filter to enable webP along with AVIF is not working
  classes/Optimization/Process/AbstractProcess.php
Labels: type: bug
