Repository wp-media/imagify-plugin, pull requests merged in 2024-03, with the labels that each got.

#820 Fix data for optimized medias without next-gen versions
  assets/js/options.js
  assets/js/options.min.js
  classes/Bulk/AbstractBulk.php
  classes/Bulk/Bulk.php
  classes/Bulk/BulkInterface.php
  classes/Bulk/CustomFolders.php
  classes/Bulk/Noop.php
  classes/Bulk/WP.php
  classes/Imagifybeat/Actions.php
  classes/Plugin.php
  classes/Stats/OptimizedMediaWithoutNextGen.php
  classes/Stats/ServiceProvider.php
  config/providers.php
  inc/3rd-party/nextgen-gallery/classes/Bulk/NGG.php
  inc/admin/upgrader.php
  inc/functions/i18n.php
  uninstall.php
  views/part-settings-webp.php
Labels: type: bug

#842 Fix number of media in the bulk optimization
  classes/Bulk/Bulk.php
Labels: type: bug, module: bulk optimization

#857 Fixes #856 Update minimum PHP version to 7.3
  .github/workflows/test.yml
  .github/workflows/test_plugin_legacy.yml
  imagify.php
  readme.txt
Labels: type: enhancement

#855 Closes #838: Fix the infinite loop of `generate missing next-gen images`
  classes/Bulk/Bulk.php
Labels: type: bug, priority: medium, AVIF

#835 Fixes #833 Delete all next-gen versions on restore original image
  classes/Optimization/Process/AbstractProcess.php
Labels: type: bug

#810 Closes #794 display the smaller size on image library data
  classes/Bulk/Bulk.php
  classes/Optimization/Data/AbstractData.php
  classes/Optimization/Data/DataInterface.php
  classes/Optimization/Data/Noop.php
Labels: type: bug

#861 Closes #837: htaccess always modified when saving settings
  classes/Avif/Display.php
  classes/Webp/Display.php
Labels: AVIF

#846 Update Next-Gen gallery compatibility for AVIF support
  inc/3rd-party/nextgen-gallery/classes/Bulk/NGG.php
  inc/3rd-party/nextgen-gallery/inc/common/attachments.php
Labels: 3rd party compatibility, AVIF
